</main>
<footer class="mt-5 bottom">
    
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">TS</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown text-center">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="http://localhost/php/proc/ecf5/proc/index.php">Acceuil</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="http://localhost/php/proc/ecf5/proc/CGV.php">CGI</a>
        </li>
        <li class="nav-item flex-end"></li>
      </ul>
    </div>
    <div class="text-right text-white col-4"> Copyright &copy; 2021 </div>
  </div>
</nav>
</footer>
</body>
</html>